
import { render, screen } from '@testing-library/react';
import { expect, test, describe } from 'vitest';
import { MarkdownRenderer } from './MarkdownRenderer';

describe('MarkdownRenderer', () => {
  test('renders basic markdown text', () => {
    render(<MarkdownRenderer content="Hello **World**" />);
    const boldElement = screen.getByText('World');
    expect(boldElement.tagName).toBe('STRONG');
    expect(screen.getByText(/Hello/)).toBeInTheDocument();
  });

  test('validates Markdown parsing edge cases including links and code', () => {
    render(
      <MarkdownRenderer 
        content={`Check this [link](https://test.com) and \`inline code\``} 
      />
    );
    const link = screen.getByRole('link', { name: 'link' });
    expect(link).toHaveAttribute('href', 'https://test.com');
    // Using standard HTML elements generated by react-markdown
    const code = screen.getByText('inline code');
    expect(code.tagName).toBe('CODE');
  });

  test('protects against XSS attacks via rehype-sanitize', () => {
    // Malicious link should be sanitized to remove javascript:
    const maliciousPayload = `[safe text](javascript:alert("hacked"))`;
    render(<MarkdownRenderer content={maliciousPayload} />);
    
    // The safe markdown should be rendered
    const linkText = screen.getByText('safe text');
    expect(linkText.tagName).toBe('A');
    
    // The href should not contain the malicious payload
    expect(linkText).not.toHaveAttribute('href', 'javascript:alert("hacked")');
  });
});
