// GENERATED by scripts/generate-embedded-migrations.ts — do not edit.
// Run `moon run backend:generate-migrations` after adding a migration.
import type { EmbeddedMigration } from './embeddedMigrations';

import path0 from '../../drizzle-sqlite/0000_mushy_kulan_gath.sql' with { type: 'file' };
import path1 from '../../drizzle-sqlite/0001_redundant_silvermane.sql' with { type: 'file' };
import path2 from '../../drizzle-sqlite/0002_normal_nightcrawler.sql' with { type: 'file' };
import path3 from '../../drizzle-sqlite/0003_huge_deathstrike.sql' with { type: 'file' };
import path4 from '../../drizzle-sqlite/0004_lazy_miss_america.sql' with { type: 'file' };
import path5 from '../../drizzle-sqlite/0005_absurd_invisible_woman.sql' with { type: 'file' };
import path6 from '../../drizzle-sqlite/0006_fantastic_pet_avengers.sql' with { type: 'file' };
import path7 from '../../drizzle-sqlite/0007_bizarre_venom.sql' with { type: 'file' };
import path8 from '../../drizzle-sqlite/0008_marvelous_namor.sql' with { type: 'file' };
import path9 from '../../drizzle-sqlite/0009_lush_wither.sql' with { type: 'file' };
import path10 from '../../drizzle-sqlite/0010_tiresome_nextwave.sql' with { type: 'file' };
import path11 from '../../drizzle-sqlite/0011_aberrant_longshot.sql' with { type: 'file' };
import path12 from '../../drizzle-sqlite/0012_red_maverick.sql' with { type: 'file' };
import path13 from '../../drizzle-sqlite/0013_good_felicia_hardy.sql' with { type: 'file' };
import path14 from '../../drizzle-sqlite/0014_handy_lila_cheney.sql' with { type: 'file' };
import path15 from '../../drizzle-sqlite/0015_lyrical_pestilence.sql' with { type: 'file' };
import path16 from '../../drizzle-sqlite/0016_pretty_eternity.sql' with { type: 'file' };
import path17 from '../../drizzle-sqlite/0017_skinny_supernaut.sql' with { type: 'file' };
import path18 from '../../drizzle-sqlite/0018_add_roles_owner_viewer.sql' with { type: 'file' };
import path19 from '../../drizzle-sqlite/0019_backfill_org_owners.sql' with { type: 'file' };
import path20 from '../../drizzle-sqlite/0020_purge_health_probe_rows.sql' with { type: 'file' };
import path21 from '../../drizzle-sqlite/0021_scope_agent_roles_to_org.sql' with { type: 'file' };
import path22 from '../../drizzle-sqlite/0022_invitation_expiry.sql' with { type: 'file' };
import path23 from '../../drizzle-sqlite/0023_api_tokens.sql' with { type: 'file' };
import path24 from '../../drizzle-sqlite/0024_task_status_position.sql' with { type: 'file' };
import path25 from '../../drizzle-sqlite/0025_fts5_search_index.sql' with { type: 'file' };
import path26 from '../../drizzle-sqlite/0026_fts5_projects_agents_comments.sql' with { type: 'file' };
import path27 from '../../drizzle-sqlite/0027_hot_query_indexes.sql' with { type: 'file' };
import path28 from '../../drizzle-sqlite/0028_users_email_optional_username.sql' with { type: 'file' };
import path29 from '../../drizzle-sqlite/0029_backfill_usernames.sql' with { type: 'file' };
import path30 from '../../drizzle-sqlite/0030_password_credentials_linked_identities.sql' with { type: 'file' };
import path31 from '../../drizzle-sqlite/0031_backfill_google_linked_identities.sql' with { type: 'file' };
import path32 from '../../drizzle-sqlite/0032_invitations_username.sql' with { type: 'file' };
import path33 from '../../drizzle-sqlite/0033_roles_teams_grants.sql' with { type: 'file' };
import path34 from '../../drizzle-sqlite/0034_seed_system_roles_and_migrate_grants.sql' with { type: 'file' };
import path35 from '../../drizzle-sqlite/0035_idempotency_keys.sql' with { type: 'file' };
import path36 from '../../drizzle-sqlite/0036_project_description.sql' with { type: 'file' };
import path37 from '../../drizzle-sqlite/0037_agent_roles_unique_name.sql' with { type: 'file' };
import path38 from '../../drizzle-sqlite/0038_artifacts_unique_names.sql' with { type: 'file' };
import path39 from '../../drizzle-sqlite/0039_task_statuses_reviewers_unique.sql' with { type: 'file' };
import path40 from '../../drizzle-sqlite/0040_project_templates_unique_name.sql' with { type: 'file' };
import path41 from '../../drizzle-sqlite/0041_seed_memory_permissions.sql' with { type: 'file' };
import path42 from '../../drizzle-sqlite/0042_beliefs_schema.sql' with { type: 'file' };
import path43 from '../../drizzle-sqlite/0043_task_notes_note_type.sql' with { type: 'file' };
import path44 from '../../drizzle-sqlite/0044_audit_log.sql' with { type: 'file' };

export const EMBEDDED_SQLITE_MIGRATIONS: EmbeddedMigration[] = [
  { tag: "0000_mushy_kulan_gath", when: 1775866918648, hash: "337fc90e67c91e887a3596fc6c376ad0cede36ddb1ee2bbcd503b3690ec4a676", path: path0 },
  { tag: "0001_redundant_silvermane", when: 1776929496665, hash: "beb1a9237f06db908c5724d8434f97259d19936244e2c40c15e395696e1e1052", path: path1 },
  { tag: "0002_normal_nightcrawler", when: 1783765069200, hash: "1ca3cec8313abca67fc5bae27b606e6649d2f1e687639a5ab272b9301ed759b5", path: path2 },
  { tag: "0003_huge_deathstrike", when: 1783766010321, hash: "b8809d23b56135a366df9e3430ca5c756502fdd021c3c2e69a516aed664386d1", path: path3 },
  { tag: "0004_lazy_miss_america", when: 1783767743829, hash: "7231d9ca9631c736db5f67bc771b8ab9b6f8780e9826f6a36f7d7a226f1cab9d", path: path4 },
  { tag: "0005_absurd_invisible_woman", when: 1783771899767, hash: "fd0608b1ba3fa7de0fefb4cbc267c24bf48800c5fd8a7ad820944ed3757fe915", path: path5 },
  { tag: "0006_fantastic_pet_avengers", when: 1783821847423, hash: "f1aacaa2b8caebc86e1b84f407f84404f286dd471c70cbbd6d41af9de2634e1c", path: path6 },
  { tag: "0007_bizarre_venom", when: 1783822475116, hash: "04a81a8be8015954c2be1dc188b5e3185c6ed92ed8be902fa7204d082e3b252d", path: path7 },
  { tag: "0008_marvelous_namor", when: 1783823056022, hash: "bb2185507c9a392950ba970819111d7390b029b2d55f57afa8ef9a124bda5564", path: path8 },
  { tag: "0009_lush_wither", when: 1783831169607, hash: "df276f6b7e46a713caef62830b552adcdf2097cdc73db15b705e75852c65f555", path: path9 },
  { tag: "0010_tiresome_nextwave", when: 1783831577487, hash: "618e6e1dbc49c4a96f9f118913eacefacdb2b5e0f33709ac4af6024fd8cb0b3a", path: path10 },
  { tag: "0011_aberrant_longshot", when: 1783841747496, hash: "ae89a378c913fb87a74a651df8288f83550e4b06f6800abecf2d1cb835138df1", path: path11 },
  { tag: "0012_red_maverick", when: 1783847485135, hash: "0b1abf2552ba55670204fb58e661c53f97f2b964f9e7dbc7d1162297cf8a3c6b", path: path12 },
  { tag: "0013_good_felicia_hardy", when: 1783933031531, hash: "a08d165a66dddcb61764526c9b9e4ced778f12f25d1fd0111c98639afe8057bc", path: path13 },
  { tag: "0014_handy_lila_cheney", when: 1783936704874, hash: "1520357a066f6bbc9ef039a5ff1c7578c1808b8891aa5901fa547267c1618f1b", path: path14 },
  { tag: "0015_lyrical_pestilence", when: 1784017944469, hash: "032d6cd5e68956af3b50153aecc577cc256678433062117fcb704b0c9b2cb912", path: path15 },
  { tag: "0016_pretty_eternity", when: 1784038028483, hash: "a8d0e9507ee83ab9b87019db83933192fee8151904cb2602eb1d787a23cefb15", path: path16 },
  { tag: "0017_skinny_supernaut", when: 1784057542634, hash: "25f672590a8bf1334054447f0907ba2883c6381d4ef383d86b7f93d35be57b16", path: path17 },
  { tag: "0018_add_roles_owner_viewer", when: 1784259388525, hash: "c4a01d84317933c01703dcbbec3e46a3720ca08e9660bfd2514c8343ce67d13c", path: path18 },
  { tag: "0019_backfill_org_owners", when: 1784259407121, hash: "5fa674571c8948ee7b01f60f1418a2945825e11b653528e8ab35e01835bfb7bf", path: path19 },
  { tag: "0020_purge_health_probe_rows", when: 1786665600000, hash: "d88260b4e1dba606f16107ac179f32b77527d33d70aaa1ce783f1df1b26c1ab1", path: path20 },
  { tag: "0021_scope_agent_roles_to_org", when: 1786665601000, hash: "8635a895e66e79ff871d93e7c1a59fd2fdda2be1b47e44086d2a62d9a7371cd9", path: path21 },
  { tag: "0022_invitation_expiry", when: 1786665602000, hash: "b1ba459dbd7fe86137ffe47db8d16b36910139b39b0f812c822081577b821bfe", path: path22 },
  { tag: "0023_api_tokens", when: 1786772023820, hash: "1c80b4ba9d91a81a770b190468135abaf5059e0e3e39f6626d2589be3133b734", path: path23 },
  { tag: "0024_task_status_position", when: 1786790000000, hash: "795e9bf2021d137ecc7a1434acd5749310b4fca2196369fbf2a095b8a38458c9", path: path24 },
  { tag: "0025_fts5_search_index", when: 1786790010000, hash: "acffe96c056692b2e0c700f47468dcf8f06f4e7929f489cbae79bb4c59d26c83", path: path25 },
  { tag: "0026_fts5_projects_agents_comments", when: 1786790020000, hash: "be1121dc1d1ef10b9c984bf01381264605b9b1b103fad9f1b83b350752a7860a", path: path26 },
  { tag: "0027_hot_query_indexes", when: 1786790030000, hash: "84af4934d0b2954a8c59780b0325ae0d871577e68bbcbd3ed9e6922c40ab7433", path: path27 },
  { tag: "0028_users_email_optional_username", when: 1786900000000, hash: "3cd1332f7fb53af2dd1b3ebb13493f0c4adbecccb3892a7a43c0ae80dc942b3a", path: path28 },
  { tag: "0029_backfill_usernames", when: 1786900010000, hash: "ec75ee8bc378b9d1262144b9239b68d6d5719d6074dcbcd56f5dd2468f5a92a4", path: path29 },
  { tag: "0030_password_credentials_linked_identities", when: 1786910000000, hash: "529446913df20b7a0cac88997355fc48f7e8ed9886b31f3256113cec30c43a19", path: path30 },
  { tag: "0031_backfill_google_linked_identities", when: 1786920000000, hash: "fae532ca800d051aafac18e2df17b9f6aaee25930ae4e6a2ab7e51d2c04cfb9d", path: path31 },
  { tag: "0032_invitations_username", when: 1786930000000, hash: "422f704307b7d639c794a473a211e94bc374af44f7415a2f8e0ee595500ee200", path: path32 },
  { tag: "0033_roles_teams_grants", when: 1787000000000, hash: "23300d384d2045ea5c28b373ffa4460463b6e44ef7900afa18aaa80931636b67", path: path33 },
  { tag: "0034_seed_system_roles_and_migrate_grants", when: 1787100000000, hash: "e58a3cf57bd645c1a91a0168ec8542277167147791e9d180e4ccc098e6556ca1", path: path34 },
  { tag: "0035_idempotency_keys", when: 1787200000000, hash: "678ba025171117f3082c88a2b6fff0052e60b5d351db17807892b6a3e4c02437", path: path35 },
  { tag: "0036_project_description", when: 1787300000000, hash: "fd8c9e84976886f1d1e230abd4e14fbea9924da0ba926f04bef7ef0e22e31407", path: path36 },
  { tag: "0037_agent_roles_unique_name", when: 1787400000000, hash: "498bcddc2a0495b129d9895237b88ec311dca627fc99eea17a5fcf64c48e2695", path: path37 },
  { tag: "0038_artifacts_unique_names", when: 1787500000000, hash: "627d230a4d1b09105bc113c0572fd4d171f0cf725efc271073e022f73d48d300", path: path38 },
  { tag: "0039_task_statuses_reviewers_unique", when: 1787600000000, hash: "43977eb2e79e1772506d9b00479a503fb1b401f9b9712157126ae96e00311f28", path: path39 },
  { tag: "0040_project_templates_unique_name", when: 1787700000000, hash: "0396f2cbc81dee427c05ae9dad39b47a063e2afce50f1696fd7ebb4a54083897", path: path40 },
  { tag: "0041_seed_memory_permissions", when: 1787800000000, hash: "391c8cae4030b015c61ed5d0e1e6b6f6070fb1d8703473b6e3a6bbf075e40f5e", path: path41 },
  { tag: "0042_beliefs_schema", when: 1787900000000, hash: "01959d2f19855fd3f46aa281b86ea7134a329ca720f340db66d71384c234ed51", path: path42 },
  { tag: "0043_task_notes_note_type", when: 1788000000000, hash: "8dc19f05466652e3cc53c934ca044a7e471ac4496ef0303a4db24abf2b54919a", path: path43 },
  { tag: "0044_audit_log", when: 1787232705138, hash: "41f17bef75ac4c854021392c79d53ba5ff96334ab62f322fbb1e454587e09e1e", path: path44 },
];
