// GENERATED by scripts/generate-embedded-migrations.ts — do not edit.
// Run `moon run backend:generate-migrations` after adding a migration.
import type { EmbeddedMigration } from './embeddedMigrations';

import path0 from '../../drizzle-sqlite/0000_mushy_kulan_gath.sql' with { type: 'file' };
import path1 from '../../drizzle-sqlite/0001_redundant_silvermane.sql' with { type: 'file' };
import path2 from '../../drizzle-sqlite/0002_normal_nightcrawler.sql' with { type: 'file' };
import path3 from '../../drizzle-sqlite/0003_huge_deathstrike.sql' with { type: 'file' };
import path4 from '../../drizzle-sqlite/0004_lazy_miss_america.sql' with { type: 'file' };
import path5 from '../../drizzle-sqlite/0005_absurd_invisible_woman.sql' with { type: 'file' };
import path6 from '../../drizzle-sqlite/0006_fantastic_pet_avengers.sql' with { type: 'file' };
import path7 from '../../drizzle-sqlite/0007_bizarre_venom.sql' with { type: 'file' };
import path8 from '../../drizzle-sqlite/0008_marvelous_namor.sql' with { type: 'file' };
import path9 from '../../drizzle-sqlite/0009_lush_wither.sql' with { type: 'file' };
import path10 from '../../drizzle-sqlite/0010_tiresome_nextwave.sql' with { type: 'file' };
import path11 from '../../drizzle-sqlite/0011_aberrant_longshot.sql' with { type: 'file' };
import path12 from '../../drizzle-sqlite/0012_red_maverick.sql' with { type: 'file' };
import path13 from '../../drizzle-sqlite/0013_good_felicia_hardy.sql' with { type: 'file' };
import path14 from '../../drizzle-sqlite/0014_handy_lila_cheney.sql' with { type: 'file' };
import path15 from '../../drizzle-sqlite/0015_lyrical_pestilence.sql' with { type: 'file' };
import path16 from '../../drizzle-sqlite/0016_pretty_eternity.sql' with { type: 'file' };
import path17 from '../../drizzle-sqlite/0017_skinny_supernaut.sql' with { type: 'file' };
import path18 from '../../drizzle-sqlite/0018_add_roles_owner_viewer.sql' with { type: 'file' };
import path19 from '../../drizzle-sqlite/0019_backfill_org_owners.sql' with { type: 'file' };
import path20 from '../../drizzle-sqlite/0020_purge_health_probe_rows.sql' with { type: 'file' };
import path21 from '../../drizzle-sqlite/0021_scope_agent_roles_to_org.sql' with { type: 'file' };
import path22 from '../../drizzle-sqlite/0022_invitation_expiry.sql' with { type: 'file' };
import path23 from '../../drizzle-sqlite/0023_api_tokens.sql' with { type: 'file' };
import path24 from '../../drizzle-sqlite/0024_task_status_position.sql' with { type: 'file' };
import path25 from '../../drizzle-sqlite/0025_fts5_search_index.sql' with { type: 'file' };
import path26 from '../../drizzle-sqlite/0026_fts5_projects_agents_comments.sql' with { type: 'file' };
import path27 from '../../drizzle-sqlite/0027_hot_query_indexes.sql' with { type: 'file' };
import path28 from '../../drizzle-sqlite/0028_users_email_optional_username.sql' with { type: 'file' };
import path29 from '../../drizzle-sqlite/0029_backfill_usernames.sql' with { type: 'file' };
import path30 from '../../drizzle-sqlite/0030_password_credentials_linked_identities.sql' with { type: 'file' };
import path31 from '../../drizzle-sqlite/0031_backfill_google_linked_identities.sql' with { type: 'file' };
import path32 from '../../drizzle-sqlite/0032_invitations_username.sql' with { type: 'file' };
import path33 from '../../drizzle-sqlite/0033_roles_teams_grants.sql' with { type: 'file' };
import path34 from '../../drizzle-sqlite/0034_seed_system_roles_and_migrate_grants.sql' with { type: 'file' };
import path35 from '../../drizzle-sqlite/0035_idempotency_keys.sql' with { type: 'file' };
import path36 from '../../drizzle-sqlite/0036_project_description.sql' with { type: 'file' };
import path37 from '../../drizzle-sqlite/0037_agent_roles_unique_name.sql' with { type: 'file' };
import path38 from '../../drizzle-sqlite/0038_artifacts_unique_names.sql' with { type: 'file' };
import path39 from '../../drizzle-sqlite/0039_task_statuses_reviewers_unique.sql' with { type: 'file' };
import path40 from '../../drizzle-sqlite/0040_project_templates_unique_name.sql' with { type: 'file' };
import path41 from '../../drizzle-sqlite/0041_seed_memory_permissions.sql' with { type: 'file' };
import path42 from '../../drizzle-sqlite/0042_beliefs_schema.sql' with { type: 'file' };
import path43 from '../../drizzle-sqlite/0043_task_notes_note_type.sql' with { type: 'file' };
import path44 from '../../drizzle-sqlite/0044_audit_log.sql' with { type: 'file' };
import path45 from '../../drizzle-sqlite/0045_task_activity.sql' with { type: 'file' };
import path46 from '../../drizzle-sqlite/0046_backfill_task_activity.sql' with { type: 'file' };
import path47 from '../../drizzle-sqlite/0047_stalled_claim_alerts.sql' with { type: 'file' };
import path48 from '../../drizzle-mysql/0000_spooky_tana_nile.sql' with { type: 'file' };
import path49 from '../../drizzle-mysql/0001_rapid_namorita.sql' with { type: 'file' };
import path50 from '../../drizzle-mysql/0002_huge_dreaming_celestial.sql' with { type: 'file' };
import path51 from '../../drizzle-mysql/0003_chubby_ricochet.sql' with { type: 'file' };
import path52 from '../../drizzle-mysql/0004_thick_white_queen.sql' with { type: 'file' };
import path53 from '../../drizzle-mysql/0005_jazzy_killmonger.sql' with { type: 'file' };
import path54 from '../../drizzle-mysql/0006_add_roles_owner_viewer.sql' with { type: 'file' };
import path55 from '../../drizzle-mysql/0007_backfill_org_owners.sql' with { type: 'file' };
import path56 from '../../drizzle-mysql/0008_scope_agent_roles_to_org.sql' with { type: 'file' };
import path57 from '../../drizzle-mysql/0009_invitation_expiry.sql' with { type: 'file' };
import path58 from '../../drizzle-mysql/0010_api_tokens.sql' with { type: 'file' };
import path59 from '../../drizzle-mysql/0011_task_status_position.sql' with { type: 'file' };
import path60 from '../../drizzle-mysql/0012_fulltext_search_index.sql' with { type: 'file' };
import path61 from '../../drizzle-mysql/0013_fulltext_projects_agents_comments.sql' with { type: 'file' };
import path62 from '../../drizzle-mysql/0014_hot_query_indexes.sql' with { type: 'file' };
import path63 from '../../drizzle-mysql/0015_users_email_optional_username.sql' with { type: 'file' };
import path64 from '../../drizzle-mysql/0016_backfill_usernames.sql' with { type: 'file' };
import path65 from '../../drizzle-mysql/0017_password_credentials_linked_identities.sql' with { type: 'file' };
import path66 from '../../drizzle-mysql/0018_backfill_google_linked_identities.sql' with { type: 'file' };
import path67 from '../../drizzle-mysql/0019_invitations_username.sql' with { type: 'file' };
import path68 from '../../drizzle-mysql/0020_roles_teams_grants.sql' with { type: 'file' };
import path69 from '../../drizzle-mysql/0021_seed_system_roles_and_migrate_grants.sql' with { type: 'file' };
import path70 from '../../drizzle-mysql/0022_idempotency_keys.sql' with { type: 'file' };
import path71 from '../../drizzle-mysql/0023_project_description.sql' with { type: 'file' };
import path72 from '../../drizzle-mysql/0024_agent_roles_unique_name.sql' with { type: 'file' };
import path73 from '../../drizzle-mysql/0025_artifacts_unique_names.sql' with { type: 'file' };
import path74 from '../../drizzle-mysql/0026_task_statuses_reviewers_unique.sql' with { type: 'file' };
import path75 from '../../drizzle-mysql/0027_project_templates_unique_name.sql' with { type: 'file' };
import path76 from '../../drizzle-mysql/0028_seed_memory_permissions.sql' with { type: 'file' };
import path77 from '../../drizzle-mysql/0029_beliefs_schema.sql' with { type: 'file' };
import path78 from '../../drizzle-mysql/0030_task_notes_note_type.sql' with { type: 'file' };
import path79 from '../../drizzle-mysql/0031_audit_log.sql' with { type: 'file' };
import path80 from '../../drizzle-mysql/0032_task_activity.sql' with { type: 'file' };
import path81 from '../../drizzle-mysql/0033_backfill_task_activity.sql' with { type: 'file' };
import path82 from '../../drizzle-mysql/0034_stalled_claim_alerts.sql' with { type: 'file' };

export const EMBEDDED_SQLITE_MIGRATIONS: EmbeddedMigration[] = [
  { tag: "0000_mushy_kulan_gath", when: 1775866918648, hash: "337fc90e67c91e887a3596fc6c376ad0cede36ddb1ee2bbcd503b3690ec4a676", path: path0 },
  { tag: "0001_redundant_silvermane", when: 1776929496665, hash: "beb1a9237f06db908c5724d8434f97259d19936244e2c40c15e395696e1e1052", path: path1 },
  { tag: "0002_normal_nightcrawler", when: 1783765069200, hash: "1ca3cec8313abca67fc5bae27b606e6649d2f1e687639a5ab272b9301ed759b5", path: path2 },
  { tag: "0003_huge_deathstrike", when: 1783766010321, hash: "b8809d23b56135a366df9e3430ca5c756502fdd021c3c2e69a516aed664386d1", path: path3 },
  { tag: "0004_lazy_miss_america", when: 1783767743829, hash: "7231d9ca9631c736db5f67bc771b8ab9b6f8780e9826f6a36f7d7a226f1cab9d", path: path4 },
  { tag: "0005_absurd_invisible_woman", when: 1783771899767, hash: "fd0608b1ba3fa7de0fefb4cbc267c24bf48800c5fd8a7ad820944ed3757fe915", path: path5 },
  { tag: "0006_fantastic_pet_avengers", when: 1783821847423, hash: "f1aacaa2b8caebc86e1b84f407f84404f286dd471c70cbbd6d41af9de2634e1c", path: path6 },
  { tag: "0007_bizarre_venom", when: 1783822475116, hash: "04a81a8be8015954c2be1dc188b5e3185c6ed92ed8be902fa7204d082e3b252d", path: path7 },
  { tag: "0008_marvelous_namor", when: 1783823056022, hash: "bb2185507c9a392950ba970819111d7390b029b2d55f57afa8ef9a124bda5564", path: path8 },
  { tag: "0009_lush_wither", when: 1783831169607, hash: "df276f6b7e46a713caef62830b552adcdf2097cdc73db15b705e75852c65f555", path: path9 },
  { tag: "0010_tiresome_nextwave", when: 1783831577487, hash: "618e6e1dbc49c4a96f9f118913eacefacdb2b5e0f33709ac4af6024fd8cb0b3a", path: path10 },
  { tag: "0011_aberrant_longshot", when: 1783841747496, hash: "ae89a378c913fb87a74a651df8288f83550e4b06f6800abecf2d1cb835138df1", path: path11 },
  { tag: "0012_red_maverick", when: 1783847485135, hash: "0b1abf2552ba55670204fb58e661c53f97f2b964f9e7dbc7d1162297cf8a3c6b", path: path12 },
  { tag: "0013_good_felicia_hardy", when: 1783933031531, hash: "a08d165a66dddcb61764526c9b9e4ced778f12f25d1fd0111c98639afe8057bc", path: path13 },
  { tag: "0014_handy_lila_cheney", when: 1783936704874, hash: "1520357a066f6bbc9ef039a5ff1c7578c1808b8891aa5901fa547267c1618f1b", path: path14 },
  { tag: "0015_lyrical_pestilence", when: 1784017944469, hash: "032d6cd5e68956af3b50153aecc577cc256678433062117fcb704b0c9b2cb912", path: path15 },
  { tag: "0016_pretty_eternity", when: 1784038028483, hash: "a8d0e9507ee83ab9b87019db83933192fee8151904cb2602eb1d787a23cefb15", path: path16 },
  { tag: "0017_skinny_supernaut", when: 1784057542634, hash: "25f672590a8bf1334054447f0907ba2883c6381d4ef383d86b7f93d35be57b16", path: path17 },
  { tag: "0018_add_roles_owner_viewer", when: 1784259388525, hash: "c4a01d84317933c01703dcbbec3e46a3720ca08e9660bfd2514c8343ce67d13c", path: path18 },
  { tag: "0019_backfill_org_owners", when: 1784259407121, hash: "5fa674571c8948ee7b01f60f1418a2945825e11b653528e8ab35e01835bfb7bf", path: path19 },
  { tag: "0020_purge_health_probe_rows", when: 1786665600000, hash: "d88260b4e1dba606f16107ac179f32b77527d33d70aaa1ce783f1df1b26c1ab1", path: path20 },
  { tag: "0021_scope_agent_roles_to_org", when: 1786665601000, hash: "8635a895e66e79ff871d93e7c1a59fd2fdda2be1b47e44086d2a62d9a7371cd9", path: path21 },
  { tag: "0022_invitation_expiry", when: 1786665602000, hash: "b1ba459dbd7fe86137ffe47db8d16b36910139b39b0f812c822081577b821bfe", path: path22 },
  { tag: "0023_api_tokens", when: 1786772023820, hash: "1c80b4ba9d91a81a770b190468135abaf5059e0e3e39f6626d2589be3133b734", path: path23 },
  { tag: "0024_task_status_position", when: 1786790000000, hash: "795e9bf2021d137ecc7a1434acd5749310b4fca2196369fbf2a095b8a38458c9", path: path24 },
  { tag: "0025_fts5_search_index", when: 1786790010000, hash: "acffe96c056692b2e0c700f47468dcf8f06f4e7929f489cbae79bb4c59d26c83", path: path25 },
  { tag: "0026_fts5_projects_agents_comments", when: 1786790020000, hash: "be1121dc1d1ef10b9c984bf01381264605b9b1b103fad9f1b83b350752a7860a", path: path26 },
  { tag: "0027_hot_query_indexes", when: 1786790030000, hash: "84af4934d0b2954a8c59780b0325ae0d871577e68bbcbd3ed9e6922c40ab7433", path: path27 },
  { tag: "0028_users_email_optional_username", when: 1786900000000, hash: "3cd1332f7fb53af2dd1b3ebb13493f0c4adbecccb3892a7a43c0ae80dc942b3a", path: path28 },
  { tag: "0029_backfill_usernames", when: 1786900010000, hash: "ec75ee8bc378b9d1262144b9239b68d6d5719d6074dcbcd56f5dd2468f5a92a4", path: path29 },
  { tag: "0030_password_credentials_linked_identities", when: 1786910000000, hash: "529446913df20b7a0cac88997355fc48f7e8ed9886b31f3256113cec30c43a19", path: path30 },
  { tag: "0031_backfill_google_linked_identities", when: 1786920000000, hash: "fae532ca800d051aafac18e2df17b9f6aaee25930ae4e6a2ab7e51d2c04cfb9d", path: path31 },
  { tag: "0032_invitations_username", when: 1786930000000, hash: "422f704307b7d639c794a473a211e94bc374af44f7415a2f8e0ee595500ee200", path: path32 },
  { tag: "0033_roles_teams_grants", when: 1787000000000, hash: "23300d384d2045ea5c28b373ffa4460463b6e44ef7900afa18aaa80931636b67", path: path33 },
  { tag: "0034_seed_system_roles_and_migrate_grants", when: 1787100000000, hash: "e58a3cf57bd645c1a91a0168ec8542277167147791e9d180e4ccc098e6556ca1", path: path34 },
  { tag: "0035_idempotency_keys", when: 1787200000000, hash: "678ba025171117f3082c88a2b6fff0052e60b5d351db17807892b6a3e4c02437", path: path35 },
  { tag: "0036_project_description", when: 1787300000000, hash: "fd8c9e84976886f1d1e230abd4e14fbea9924da0ba926f04bef7ef0e22e31407", path: path36 },
  { tag: "0037_agent_roles_unique_name", when: 1787400000000, hash: "498bcddc2a0495b129d9895237b88ec311dca627fc99eea17a5fcf64c48e2695", path: path37 },
  { tag: "0038_artifacts_unique_names", when: 1787500000000, hash: "627d230a4d1b09105bc113c0572fd4d171f0cf725efc271073e022f73d48d300", path: path38 },
  { tag: "0039_task_statuses_reviewers_unique", when: 1787600000000, hash: "43977eb2e79e1772506d9b00479a503fb1b401f9b9712157126ae96e00311f28", path: path39 },
  { tag: "0040_project_templates_unique_name", when: 1787700000000, hash: "0396f2cbc81dee427c05ae9dad39b47a063e2afce50f1696fd7ebb4a54083897", path: path40 },
  { tag: "0041_seed_memory_permissions", when: 1787800000000, hash: "391c8cae4030b015c61ed5d0e1e6b6f6070fb1d8703473b6e3a6bbf075e40f5e", path: path41 },
  { tag: "0042_beliefs_schema", when: 1787900000000, hash: "01959d2f19855fd3f46aa281b86ea7134a329ca720f340db66d71384c234ed51", path: path42 },
  { tag: "0043_task_notes_note_type", when: 1788000000000, hash: "8dc19f05466652e3cc53c934ca044a7e471ac4496ef0303a4db24abf2b54919a", path: path43 },
  { tag: "0044_audit_log", when: 1787232705138, hash: "41f17bef75ac4c854021392c79d53ba5ff96334ab62f322fbb1e454587e09e1e", path: path44 },
  { tag: "0045_task_activity", when: 1788100000000, hash: "4505df255647148a50a9faedee0ac9b43873a7d5a35fd14f981346292e3e0915", path: path45 },
  { tag: "0046_backfill_task_activity", when: 1788200000000, hash: "d9278ef188ee1740006462f77014d20cb95b442553f4a6c73872356f6db44657", path: path46 },
  { tag: "0047_stalled_claim_alerts", when: 1788300000000, hash: "c067788f41a68f3e4b0741adab5937061b9d91647623f79910b695c5f8d074e2", path: path47 },
];

export const EMBEDDED_MYSQL_MIGRATIONS: EmbeddedMigration[] = [
  { tag: "0000_spooky_tana_nile", when: 1783851552271, hash: "0c390aee091493b713071d81aceae79960a61f198819a272faa42ff83ea53df7", path: path48 },
  { tag: "0001_rapid_namorita", when: 1783933054771, hash: "5c72d64b3c59484325a98d48f4139d806d595c69638f6233c43ec2b436f8d3c8", path: path49 },
  { tag: "0002_huge_dreaming_celestial", when: 1783936708277, hash: "2aebc4f5d6ac1b58a2161c85583cf73e6302cd1dea4f48e3fd62938e53cb2d75", path: path50 },
  { tag: "0003_chubby_ricochet", when: 1784017981443, hash: "5fd8248c97bb206ec196c10cabca04b4fe48b1a6ff47a3dec9f9cf679cd71fec", path: path51 },
  { tag: "0004_thick_white_queen", when: 1784038035530, hash: "952caf3cb59da1c8d21e4f5c8b6cf2404c6b77044457e7414aafde9965db3ce1", path: path52 },
  { tag: "0005_jazzy_killmonger", when: 1784057548432, hash: "25f672590a8bf1334054447f0907ba2883c6381d4ef383d86b7f93d35be57b16", path: path53 },
  { tag: "0006_add_roles_owner_viewer", when: 1784259397844, hash: "921e35263cbad593ce76c4edef78e4e04dda997e7f700678b1c29e9606975f21", path: path54 },
  { tag: "0007_backfill_org_owners", when: 1784259407596, hash: "47f1a21b0a994bb4685a9258c9af7bb20785b3c33be92637bfa3c4461670138c", path: path55 },
  { tag: "0008_scope_agent_roles_to_org", when: 1784259408596, hash: "9776c34cb60dc435135f32516d3ad60c690634776812b1f0d7998b2b5a5e3365", path: path56 },
  { tag: "0009_invitation_expiry", when: 1784259409596, hash: "62698d2cd7c5e664be7061d42804b002f33df5df300a8a9cac432d4be4e2c49f", path: path57 },
  { tag: "0010_api_tokens", when: 1786772053171, hash: "72f48554eb4d96ae06333b64f8b11a9b7b65b50f447cb4d896c7015e654e2584", path: path58 },
  { tag: "0011_task_status_position", when: 1786790000000, hash: "bb493a74a5d9263af0acbd893b220c21a9fe4a385b66b260dd7724d61b37c044", path: path59 },
  { tag: "0012_fulltext_search_index", when: 1786800000000, hash: "e22040069b6e4c2dd98c092b2b151192cf04a464c08801ab695e5a6eb092f556", path: path60 },
  { tag: "0013_fulltext_projects_agents_comments", when: 1786800010000, hash: "9253d4192af1987a765c9c44a26c314ff3753efdf4c7d197fc3cf8d92097f092", path: path61 },
  { tag: "0014_hot_query_indexes", when: 1786800020000, hash: "040fa605e0ece1b41aae0a66f28ac1e8d2e9efbcf4e1c9db96523f48ca30b6fb", path: path62 },
  { tag: "0015_users_email_optional_username", when: 1786900000000, hash: "25d1090b615f9ee2cfeab024ed037664fa04352da3210b2fc2d8a593ed83b95e", path: path63 },
  { tag: "0016_backfill_usernames", when: 1786900010000, hash: "fafe98412bd1b3ddf8840a6b9a89fb923281a52a3817e9331e5350815c0cf422", path: path64 },
  { tag: "0017_password_credentials_linked_identities", when: 1786910000000, hash: "0177be6f3598eb5f9c9f8ea8d39cba91a3c4914ac3fc3673c76cf4d7c01cee65", path: path65 },
  { tag: "0018_backfill_google_linked_identities", when: 1786920000000, hash: "91e04af84152af1622562d513c1a988662f4f1c34ea67ec7fd2abb0dbb938618", path: path66 },
  { tag: "0019_invitations_username", when: 1786930000000, hash: "be0407e6aba4b6301813e9bb6bf84a684710e8d9dae8a42b3d06906629c78585", path: path67 },
  { tag: "0020_roles_teams_grants", when: 1787000000000, hash: "29da679aeb07a75bdcd7e1e3024de046b0474dfc5dbb9ff1956f81d5f9f050c6", path: path68 },
  { tag: "0021_seed_system_roles_and_migrate_grants", when: 1787100000000, hash: "2f103282bc886d8138261da9df7f60538a6640c47d6e42e80d363191964ab74c", path: path69 },
  { tag: "0022_idempotency_keys", when: 1787200000000, hash: "df4b9812695921ac5837711fbadcd008840e1f23a605f287c066dc4463697837", path: path70 },
  { tag: "0023_project_description", when: 1787300000000, hash: "d03d4e574a640b5deebf8f478f2791ad38cb99ef6882d35b4e19c3da5ed014cf", path: path71 },
  { tag: "0024_agent_roles_unique_name", when: 1787400000000, hash: "9594e0169d9924e248c64ec5376493c50fc8f92e8bcff4b3b8e1338bd0d9fb8e", path: path72 },
  { tag: "0025_artifacts_unique_names", when: 1787500000000, hash: "435099a3720a0f18bfcbb1f34460afd9869d17b16d4dcc2ea878972e279ce9fd", path: path73 },
  { tag: "0026_task_statuses_reviewers_unique", when: 1787600000000, hash: "7dc10f30341837660036d3af1aa7103bf14fc88316542c223abc0732e6c18a26", path: path74 },
  { tag: "0027_project_templates_unique_name", when: 1787700000000, hash: "ec5fce313361a2628a5be28d81f86350809a2bf84a54895957531da07dd72a60", path: path75 },
  { tag: "0028_seed_memory_permissions", when: 1787800000000, hash: "cb167829fd30e8ee88814d86250fbe12e0eca886db7b476da3c0f32f48323c0e", path: path76 },
  { tag: "0029_beliefs_schema", when: 1787900000000, hash: "2ea153137c5d731790a58820fb20524b4d7dd298f3a90cf631d3eda9321e9bce", path: path77 },
  { tag: "0030_task_notes_note_type", when: 1788000000000, hash: "e7f35953eefb1cdf9012e25bf5b44318f872ef3b5e023156c61a34c008673259", path: path78 },
  { tag: "0031_audit_log", when: 1787232705139, hash: "6b92ddd135d993c76fc7cabe735e3d0d1ce5048bb0acdfed255c73d713788828", path: path79 },
  { tag: "0032_task_activity", when: 1788100000000, hash: "5b5d77254349e09939e52ad156d714da44689e87844c7f10f18c40112c9e4b49", path: path80 },
  { tag: "0033_backfill_task_activity", when: 1788200000000, hash: "8f361a2695fa075c1eb282b43d6a8bf7d15dd225ed67ea2f564709a2a2f5eae5", path: path81 },
  { tag: "0034_stalled_claim_alerts", when: 1788300000000, hash: "c090803e8679e557146ea8193e5502c2d972aaa5a45ab440e68a36130c4c1379", path: path82 },
];
