#!/usr/bin/env bun
/**
 * Generates the module that carries the SQLite migrations into the binary
 * (M09-T01).
 *
 * `drizzle-orm`'s migrator reads `./drizzle-sqlite` from the *working
 * directory* at runtime. That is fine for `moon run dev`, and fatal for a
 * single binary: copied to an empty directory, there is no folder to read and
 * the first run dies before it can create its own database.
 *
 * The generated module imports each `.sql` with `{ type: 'file' }` rather than
 * inlining its contents. `--compile` carries the file into the binary and the
 * import yields a `/$bunfs/` path; running from source it yields the real one.
 * Either way `Bun.file(path)` reads it, so the SQL stays in the files
 * drizzle-kit writes and this generated module stays a reviewable list rather
 * than a megabyte of duplicated schema.
 *
 * `{ type: 'text' }` would be the obvious choice and is the wrong one: only
 * the *bundler* inlines it. Run from source, the import yields the path
 * instead of the contents, and every migration becomes a one-line SQL syntax
 * error — which is exactly how this was found.
 *
 * Run by `moon run backend:generate-migrations`, and checked by
 * `embeddedMigrations.test.ts`, which regenerates and compares — adding a
 * migration without regenerating is a failing test, not a binary that
 * silently ships without it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const backendRoot = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Both dialects, for the same reason and found the same way. T01 embedded only
 * SQLite, because the standalone binary was the case in front of us; the
 * container image then started, tried to read `./drizzle-mysql` from a working
 * directory that has no such folder, and died on the first boot of the compose
 * stack (M11-T07). A compiled artefact carries its schema or it does not.
 */
export const DIALECTS = [
  { dialect: 'sqlite' as const, dir: 'drizzle-sqlite', constant: 'EMBEDDED_SQLITE_MIGRATIONS' },
  { dialect: 'mysql' as const, dir: 'drizzle-mysql', constant: 'EMBEDDED_MYSQL_MIGRATIONS' },
];

const OUTPUT = join(backendRoot, 'src/db/embeddedMigrations.generated.ts');

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
}

export function renderModule(
  perDialect: Array<{ dir: string; constant: string; entries: JournalEntry[]; hashes: Record<string, string> }>,
): string {
  const imports: string[] = [];
  const blocks: string[] = [];
  let n = 0;

  for (const { dir, constant, entries, hashes } of perDialect) {
    const rows: string[] = [];
    for (const entry of entries) {
      const alias = `path${n++}`;
      imports.push(`import ${alias} from '../../${dir}/${entry.tag}.sql' with { type: 'file' };`);
      rows.push(
        `  { tag: ${JSON.stringify(entry.tag)}, when: ${entry.when}, hash: ${JSON.stringify(hashes[entry.tag])}, path: ${alias} },`,
      );
    }
    blocks.push(`export const ${constant}: EmbeddedMigration[] = [\n${rows.join('\n')}\n];`);
  }

  return `// GENERATED by scripts/generate-embedded-migrations.ts — do not edit.
// Run \`moon run backend:generate-migrations\` after adding a migration.
import type { EmbeddedMigration } from './embeddedMigrations';

${imports.join('\n')}

${blocks.join('\n\n')}
`;
}

/** Reads the journal and hashes each migration exactly as drizzle does. */
export function collect(migrationsDir: string): { entries: JournalEntry[]; hashes: Record<string, string> } {
  const journal = JSON.parse(readFileSync(join(migrationsDir, 'meta/_journal.json'), 'utf8'));
  const entries: JournalEntry[] = journal.entries;
  const hashes: Record<string, string> = {};
  for (const entry of entries) {
    const sql = readFileSync(join(migrationsDir, `${entry.tag}.sql`), 'utf8');
    // sha256 of the whole file, which is what drizzle stores in
    // `__drizzle_migrations.hash`. Matching it is the point: an existing
    // database migrated by drizzle-kit must not have everything re-applied
    // the first time it is opened by the binary.
    hashes[entry.tag] = createHash('sha256').update(sql).digest('hex');
  }
  return { entries, hashes };
}

export function generate(root = backendRoot): string {
  return renderModule(
    DIALECTS.map(({ dir, constant }) => ({ dir, constant, ...collect(join(root, dir)) })),
  );
}

if (import.meta.main) {
  writeFileSync(OUTPUT, generate());
  for (const { dialect, dir } of DIALECTS) {
    console.log(`embedded ${collect(join(backendRoot, dir)).entries.length} ${dialect} migrations`);
  }
  console.log(`-> ${OUTPUT}`);
}
