#!/usr/bin/env bun
/**
 * Generates the module that carries the SQLite migrations into the binary
 * (M09-T01).
 *
 * `drizzle-orm`'s migrator reads `./drizzle-sqlite` from the *working
 * directory* at runtime. That is fine for `moon run dev`, and fatal for a
 * single binary: copied to an empty directory, there is no folder to read and
 * the first run dies before it can create its own database.
 *
 * The generated module imports each `.sql` with `{ type: 'file' }` rather than
 * inlining its contents. `--compile` carries the file into the binary and the
 * import yields a `/$bunfs/` path; running from source it yields the real one.
 * Either way `Bun.file(path)` reads it, so the SQL stays in the files
 * drizzle-kit writes and this generated module stays a reviewable list rather
 * than a megabyte of duplicated schema.
 *
 * `{ type: 'text' }` would be the obvious choice and is the wrong one: only
 * the *bundler* inlines it. Run from source, the import yields the path
 * instead of the contents, and every migration becomes a one-line SQL syntax
 * error — which is exactly how this was found.
 *
 * Run by `moon run backend:generate-migrations`, and checked by
 * `embeddedMigrations.test.ts`, which regenerates and compares — adding a
 * migration without regenerating is a failing test, not a binary that
 * silently ships without it.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const backendRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const MIGRATIONS_DIR = join(backendRoot, 'drizzle-sqlite');
const OUTPUT = join(backendRoot, 'src/db/embeddedMigrations.generated.ts');

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
}

export function renderModule(entries: JournalEntry[], hashes: Record<string, string>): string {
  const imports = entries
    .map((e, i) => `import path${i} from '../../drizzle-sqlite/${e.tag}.sql' with { type: 'file' };`)
    .join('\n');

  const rows = entries
    .map(
      (e, i) =>
        `  { tag: ${JSON.stringify(e.tag)}, when: ${e.when}, hash: ${JSON.stringify(hashes[e.tag])}, path: path${i} },`,
    )
    .join('\n');

  return `// GENERATED by scripts/generate-embedded-migrations.ts — do not edit.
// Run \`moon run backend:generate-migrations\` after adding a migration.
import type { EmbeddedMigration } from './embeddedMigrations';

${imports}

export const EMBEDDED_SQLITE_MIGRATIONS: EmbeddedMigration[] = [
${rows}
];
`;
}

/** Reads the journal and hashes each migration exactly as drizzle does. */
export function collect(migrationsDir: string): { entries: JournalEntry[]; hashes: Record<string, string> } {
  const journal = JSON.parse(readFileSync(join(migrationsDir, 'meta/_journal.json'), 'utf8'));
  const entries: JournalEntry[] = journal.entries;
  const hashes: Record<string, string> = {};
  for (const entry of entries) {
    const sql = readFileSync(join(migrationsDir, `${entry.tag}.sql`), 'utf8');
    // sha256 of the whole file, which is what drizzle stores in
    // `__drizzle_migrations.hash`. Matching it is the point: an existing
    // database migrated by drizzle-kit must not have everything re-applied
    // the first time it is opened by the binary.
    hashes[entry.tag] = createHash('sha256').update(sql).digest('hex');
  }
  return { entries, hashes };
}

export function generate(migrationsDir = MIGRATIONS_DIR): string {
  const { entries, hashes } = collect(migrationsDir);
  return renderModule(entries, hashes);
}

if (import.meta.main) {
  writeFileSync(OUTPUT, generate());
  const { entries } = collect(MIGRATIONS_DIR);
  console.log(`embedded ${entries.length} sqlite migrations -> ${OUTPUT}`);
}
