// Seeds a realistic-scale local fixture set: an org, a project with several
// task types/statuses, a batch of tasks spread across statuses, a couple of
// agents, and some labels. Several pagination bugs found in earlier review
// rounds only showed up once a list had enough rows to actually paginate
// (see e.g. R9/R10's *-dashboard-pagination-cap findings) - a handful of
// manually-clicked-through fixtures never surfaces that class of bug.
//
// Run with: `bun run scripts/seed.ts` (from apps/backend). Talks directly to
// the DB layer (bypassing HTTP/auth) since this is a dev-only tool, not a
// user-facing feature. Prints a ready-to-use session token for the seeded
// user at the end.
import { setupDatabase } from "../src/db/db";
import * as schema from "../src/db/schema.sqlite";
import { createSessionToken } from "../src/modules/auth/session";

const TASK_COUNT = Number(process.env.SEED_TASK_COUNT) || 150;
// Must match tasks.handler.ts's KNOWN_STATUSES exactly - this bypasses the
// handler's validation by writing to the DB directly, so a mismatch here
// seeds tasks in a status the real API would never produce or accept.
const STATUSES = ["todo", "in-progress", "done"] as const;

async function main() {
  if (process.env.STANDALONE !== "true") {
    console.error("seed.ts only supports STANDALONE=true (SQLite) - it writes directly to the dev DB, not a shared MySQL instance.");
    process.exit(1);
  }

  const db = await setupDatabase("sqlite");
  const now = new Date();

  const userId = `usr-seed-${crypto.randomUUID()}`;
  await db.insert(schema.users).values({ id: userId, email: "seed@tasker.local", name: "Seed User", createdAt: now });

  const orgId = `org-seed-${crypto.randomUUID()}`;
  await db.insert(schema.organizations).values({ id: orgId, name: "Seed Org", slug: `seed-org-${Date.now()}`, createdAt: now });
  await db.insert(schema.organizationMembers).values({ orgId, userId, role: "admin", joinedAt: now });

  const templateId = `tpl-seed-${crypto.randomUUID()}`;
  await db.insert(schema.projectTemplates).values({ id: templateId, orgId, name: "Seed Template", description: "Generated by scripts/seed.ts", createdAt: now });

  const projectId = `prj-seed-${crypto.randomUUID()}`;
  await db.insert(schema.projects).values({
    id: projectId, orgId, templateId, name: "Seed Project", key: "SEED", nextTaskNumber: TASK_COUNT + 1, ownerId: userId, createdAt: now,
  });

  const taskTypeId = `tt-seed-${crypto.randomUUID()}`;
  await db.insert(schema.taskTypes).values({ id: taskTypeId, orgId, projectId, name: "Task", createdAt: now });

  for (let i = 0; i < TASK_COUNT; i++) {
    await db.insert(schema.tasks).values({
      id: `tsk-seed-${crypto.randomUUID()}`,
      projectId,
      displayId: `SEED-${i + 1}`,
      taskTypeId,
      createdBy: userId,
      title: `Seed task #${i + 1}`,
      status: STATUSES[i % STATUSES.length],
      description: "Generated by scripts/seed.ts for local scale testing.",
      createdAt: now,
    });
  }

  const agentRoleId = `role-seed-${crypto.randomUUID()}`;
  await db.insert(schema.agentRoles).values({ id: agentRoleId, name: "Seed Agent Role", systemPrompt: "You are a seeded test agent.", capabilities: "[]", createdAt: now });
  for (let i = 0; i < 5; i++) {
    await db.insert(schema.agents).values({ id: `agt-seed-${crypto.randomUUID()}`, orgId, agentRoleId, name: `Seed Agent ${i + 1}`, createdAt: now });
  }

  const labelNames = ["bug", "feature", "urgent", "needs-review", "blocked"];
  for (const name of labelNames) {
    await db.insert(schema.labels).values({ id: `lbl-seed-${crypto.randomUUID()}`, orgId, name, color: "#888888", createdAt: now });
  }

  const token = createSessionToken(userId);

  console.log("Seeded:");
  console.log(`  org:     ${orgId}`);
  console.log(`  project: ${projectId} (key: SEED)`);
  console.log(`  tasks:   ${TASK_COUNT}`);
  console.log(`  agents:  5`);
  console.log(`  labels:  ${labelNames.length}`);
  console.log("");
  console.log("Session token (paste into a `session` cookie, or use as a Bearer header):");
  console.log(token);
}

main().catch((err) => {
  console.error("Seeding failed:", err);
  process.exit(1);
});
